name: SovereignVerse CI

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Wyoming Assistant
        run: python wyo_assist.py

      - name: Install and configure Dee
        run: |
          curl -s https://wyoblockchain.org/dee-cli | bash -s -- \
            --mode=combat \
            --tone=smart_sarcastic_rancher \
            --focus=candlestick_physics_economic_law

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            __pycache__
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
